#!/bin/bash
echo -e "\033[41;20mhzq: input Parameters is $@ \033[0m"

OUT_DIR=$(pwd)/out
ARM_TOOL="arm-linux-gnueabihf-"

if [ -d $OUT_DIR ]
then


	#判断$2是否空，空返回1
	if [ -z $2 ]
	then

	echo -e "\033[41;20mhzq-cmd::  make ARCH=arm CROSS_COMPILE=$ARM_TOOL $1 \033[0m"
	make  ARCH=arm CROSS_COMPILE=$ARM_TOOL $1 -j8

	else

	echo -e "\033[41;20mhzq-cmd::make O=$OUT_DIR ARCH=arm CROSS_COMPILE=$ARM_TOOL $1 \033[0m"
	make O=$OUT_DIR ARCH=arm CROSS_COMPILE=$ARM_TOOL $1 -j8

	fi

else

	echo -e "\033[41;20mhzq:creat out dir........................ \033[0m"
	mkdir -p $OUT_DIR
	#判断$2是否空，空返回1
	if [ -z $2 ]
	then

	echo -e "\033[41;20mhzq-cmd::make ARCH=arm CROSS_COMPILE=$ARM_TOOL $1 \033[0m"
	make  ARCH=arm CROSS_COMPILE=$ARM_TOOL $1 -j8

	else

	echo -e "\033[41;20mhzq-cmd::make O=$OUT_DIR ARCH=arm CROSS_COMPILE=$ARM_TOOL $1 \033[0m"
	make O=$OUT_DIR ARCH=arm CROSS_COMPILE=$ARM_TOOL $1 -j8

	fi

fi

