#!/bin/bash
echo "hzq: input Parameters is $1"

OUT_DIR=$(pwd)/out
ARM_TOOL="arm-linux-gnueabihf-"

if [ -d $OUT_DIR ]
then

echo -e "\033[41;20m####################################################################################\033[0m"
echo ""
echo -e "\033[41;20mhzq:$OUT_DIR has exist ! it will be Compiled directly \033[0m"
echo -e "\033[41;20mhzq:cmd is make O=$OUT_DIR ARCH=arm CROSS_COMPILE=$ARM_TOOL $1 \033[0m"
echo ""
echo -e "\033[41;20m####################################################################################\033[0m"
echo ""

make O=$OUT_DIR ARCH=arm CROSS_COMPILE=$ARM_TOOL $1 -j8

else

echo ""
echo -e "\033[41;20mwarring:has not  \"$OUT_DIR\" !!!!\033[0m"
echo -e "\033[41;20mNow will creat  \"$OUT_DIR\" and Compiled directly!!!\033[0m"
echo -e "\033[41;20mhzq:cmd is make O=$OUT_DIR ARCH=arm CROSS_COMPILE=$ARM_TOOL $1 \033[0m"
echo ""

mkdir -p $OUT_DIR
make O=$OUT_DIR ARCH=arm CROSS_COMPILE=$ARM_TOOL $1 -j8
fi


