#!/bin/bash
echo -e "\033[41;20mhzq: input Parameters is $@\033[0m"

OUT_DIR=$(pwd)/out
ARM_TOOL="arm-arago-linux-gnueabi-"

if [ -d $OUT_DIR ]
then


	#判断$2是否空，空返回1
	if [ -z $2 ]
	then

	echo -e "\033[41;20mhzq-cmd::  make ARCH=arm CROSS_COMPILE=$ARM_TOOL $1 \033[0m"
	make  ARCH=arm CROSS_COMPILE=$ARM_TOOL $1 -j8

	else

	echo -e "\033[41;20mhzq-cmd::make O=$OUT_DIR ARCH=arm CROSS_COMPILE=$ARM_TOOL $1 \033[0m"
	make O=$OUT_DIR ARCH=arm CROSS_COMPILE=$ARM_TOOL $1 -j8

	fi

else

	echo -e "\033[41;20mhzq:creat out dir........................ \033[0m"
	mkdir -p $OUT_DIR
	#判断$2是否空，空返回1
	if [ -z $2 ]
	then

	echo -e "\033[41;20mhzq-cmd::make ARCH=arm CROSS_COMPILE=$ARM_TOOL $1 \033[0m"
	make  ARCH=arm CROSS_COMPILE=$ARM_TOOL $1 -j8

	else

	echo -e "\033[41;20mhzq-cmd::make O=$OUT_DIR ARCH=arm CROSS_COMPILE=$ARM_TOOL $1 \033[0m"
	make O=$OUT_DIR ARCH=arm CROSS_COMPILE=$ARM_TOOL $1 -j8

	fi

fi

#定义命令数组
#arry=( mrproper am335x_evm_defconfig menuconfig uImage modules ) #数组下标从0开始
#case $1 in
#0|1|2|3|4)
#echo -e "\033[41;20m####################################################################################\033[0m"
#echo ""
#echo -e "\033[41;20mhzq:cmd is make O=$OUT_DIR ARCH=arm CROSS_COMPILE=$ARM_TOOL ${arry[$1]} .......\033[0m"
#echo ""
#echo -e "\033[41;20m####################################################################################\033[0m"
#echo ""
#make O=$OUT_DIR ARCH=arm CROSS_COMPILE=$ARM_TOOL ${arry[$1]} -j8
#;;
#*)
#echo -e "\033[41;20m cmd is 0=mrproper 1=am335x_evm_defconfig 2=menuconfig 3=uImage 4=modules \033[0m"
#;;
#esac

